# import uvicorn
# from openenv.core.env_server import create_fastapi_app
# from server.environment import DebateEnvironment
# from schema.schemas import DebateAction,DebateObservation

# from fastapi.responses import RedirectResponse

# app = create_fastapi_app(
#     DebateEnvironment, 
#     action_cls=DebateAction, 
#     observation_cls=DebateObservation
# )

# @app.get("/")
# def read_root():
#     return RedirectResponse(url="/docs")

# def main():
#     uvicorn.run("server.app:app", host="0.0.0.0", port=7860)

# if __name__ == "__main__":
#     main()


import gradio as gr
from fastapi import FastAPI
import uvicorn

# Import your actual environment
from environment import DebateEnvironment 
from schema.schemas import DebateAction

# Initialize FastAPI and your Environment
app = FastAPI()
env = DebateEnvironment()

# ==========================================
# PART 1: FASTAPI ENDPOINTS (For Auto-Grader)
# ==========================================

@app.post("/reset")
def reset_api(topic: str = "Universal Basic Income is necessary"):
    return env.reset(topic)

@app.post("/step")
def step_api(action: DebateAction):
    return env.step(action)

# ==========================================
# PART 2: UI LOGIC & HTML RENDERERS
# ==========================================

# Pre-written high-quality arguments to save judges time during evaluation
AUTO_FILL_DATA = {
    "STANDBY": ("OPENING", "Universal Basic Income is an essential policy for the future economy. As automation and AI rapidly displace traditional jobs, UBI ensures a fundamental safety net, preventing mass poverty and maintaining consumer demand."),
    "OPENING": ("CHALLENGE", "While critics argue that UBI is too expensive or causes inflation, economic models show that when funded through progressive taxation—like a wealth tax—it does not trigger hyperinflation. It simply redistributes capital locally."),
    "CHALLENGE": ("REBUTTAL", "Furthermore, the assumption that UBI destroys the incentive to work is contradicted by real-world data. Pilot programs demonstrate that freed from survival stress, people invest more time in education and small businesses."),
    "REBUTTAL": ("CONSOLIDATION", "Looking at the macroeconomic scale, the velocity of money generated by UBI actually creates a robust, bottom-up economic stimulus that far outweighs the initial taxation costs required to implement it."),
    "CONSOLIDATION": ("CLOSING", "Ultimately, Universal Basic Income is not just a welfare handout; it is a necessary economic stabilizer for the 21st century. It enables human innovation and builds a resilient society against technological disruption."),
    "CLOSING": ("CLOSING", "The debate has reached its natural conclusion.")
}

def render_metric_card(title, value, color_hex):
    return f"""
    <div style="background-color: #2b2b36; border-radius: 8px; padding: 15px; border-top: 4px solid {color_hex}; height: 100%; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <div style="font-size: 0.75rem; text-transform: uppercase; color: #9ca3af; font-weight: bold; letter-spacing: 0.05em; margin-bottom: 5px;">{title}</div>
        <div style="font-size: 1.5rem; font-weight: bold; color: white;">{value}</div>
    </div>
    """

def render_pills(difficulty, phase):
    """Renders the dark metadata tags (e.g. [ DIFFICULTY: medium ])"""
    return f"""
    <div style='display: flex; gap: 10px; margin-bottom: 15px; font-family: monospace;'>
        <span style='background: #374151; color: #d1d5db; padding: 4px 10px; border-radius: 4px; font-size: 12px; border: 1px solid #4b5563;'>DIFFICULTY: {difficulty}</span>
        <span style='background: #374151; color: #d1d5db; padding: 4px 10px; border-radius: 4px; font-size: 12px; border: 1px solid #4b5563;'>ENVIRONMENT PHASE: {phase}</span>
    </div>
    """

def render_timeline(history_data):
    """Generates the custom step-by-step Action Timeline from the user's screenshot"""
    if not history_data:
        return "<div style='padding: 20px; text-align: center; color: #9ca3af; border: 1px dashed #4b5563; border-radius: 6px;'>No actions yet. Run Reset, then Execute step.</div>"
    
    html = "<div style='display: flex; flex-direction: column; gap: 10px;'>"
    for step_idx, item in enumerate(history_data):
        color = "#22c55e" if float(item['reward']) >= 0 else "#ef4444"
        sign = "+" if float(item['reward']) > 0 else ""
        html += f"""
        <div style='background: #1f2937; border: 1px solid #374151; border-radius: 8px; padding: 15px;'>
            <div style='display: flex; justify-content: space-between; margin-bottom: 10px;'>
                <strong style='color: white; font-size: 14px;'>Step {step_idx}: {item['phase_tag'].lower()}</strong>
                <strong style='color: {color};'>{sign}{item['reward']:.2f}</strong>
            </div>
            <div style='color: #9ca3af; font-size: 13px; margin-bottom: 8px;'><b>Agent:</b> {item['argument']}</div>
            <div style='color: #d1d5db; font-size: 13px; border-left: 3px solid #4b5563; padding-left: 10px;'><b>Opponent:</b> {item['opponent']}</div>
        </div>
        """
    html += "</div>"
    return html

def auto_fill_action(current_phase):
    """Fetches the ideal next move based on the current environment phase"""
    phase_tag, argument = AUTO_FILL_DATA.get(current_phase, ("OPENING", ""))
    return phase_tag, argument

def reset_env_ui(topic, difficulty):
    obs = env.reset(topic)
    
    timeline_data = [] # Clear history
    
    return [
        render_metric_card("LAST STEP REWARD", "0.00", "#3b82f6"),
        render_metric_card("TOTAL REWARD", "0.00", "#f97316"),
        render_metric_card("SCORE (SEMANTICS)", "0%", "#22c55e"),
        render_metric_card("STATUS", "ACTIVE", "#6b7280"),
        render_pills(difficulty, obs.phase),
        f"<i>{obs.opponent_challenge}</i>",
        render_timeline(timeline_data),
        timeline_data,
        0.0,
        obs.phase # Save internal current phase
    ]

def step_env_ui(argument, phase_tag, timeline_data, total_reward, difficulty):
    if not argument.strip():
        return [gr.update() for _ in range(9)]

    action = DebateAction(argument=argument, phase_tag=phase_tag)
    obs = env.step(action)
    
    bot_message = obs.opponent_challenge if obs.opponent_challenge else "Episode Terminated."
    new_total = total_reward + float(obs.reward)
    
    # Update custom timeline state
    timeline_data.append({
        "phase_tag": phase_tag,
        "argument": argument,
        "opponent": bot_message,
        "reward": float(obs.reward)
    })
    
    status_text = "TERMINATED" if obs.done else "ACTIVE"
    status_color = "#ef4444" if obs.done else "#6b7280"
    
    return [
        render_metric_card("LAST STEP REWARD", f"{obs.reward:.2f}", "#3b82f6"),
        render_metric_card("TOTAL REWARD", f"{new_total:.2f}", "#f97316"),
        render_metric_card("SCORE (SEMANTICS)", f"{(new_total/5)*100:.0f}%", "#22c55e"), # Pseudo % score
        render_metric_card("STATUS", status_text, status_color),
        render_pills(difficulty, obs.phase),
        f"<i>{bot_message}</i>",
        render_timeline(timeline_data),
        timeline_data,
        new_total,
        obs.phase # Save internal current phase
    ]

# ==========================================
# PART 3: GRADIO DASHBOARD LAYOUT
# ==========================================

theme = gr.themes.Default(neutral_hue="slate").set(
    body_background_fill="#111827", body_text_color="#f3f4f6",
    block_background_fill="#1f2937", block_border_color="#374151"
)

with gr.Blocks(theme=theme, css=".gradio-container {max-width: 1000px !important;}") as demo:
    
    # Hidden States
    timeline_state = gr.State(value=[])
    total_reward_state = gr.State(value=0.0)
    current_phase_state = gr.State(value="STANDBY")
    
    # 1. Header & Metric Cards
    gr.Markdown("## 🛡️ Strategic Argument Command Center")
    with gr.Row():
        last_step_card = gr.HTML(render_metric_card("LAST STEP REWARD", "--", "#3b82f6"))
        total_rew_card = gr.HTML(render_metric_card("TOTAL REWARD", "--", "#f97316"))
        score_card = gr.HTML(render_metric_card("SCORE", "--", "#22c55e"))
        status_card = gr.HTML(render_metric_card("STATUS", "STANDBY", "#6b7280"))

    # 2. Current State (Replicates the "Current Ticket" box)
    gr.Markdown("### Current Debate State")
    with gr.Group():
        pills_html = gr.HTML(render_pills("Medium", "STANDBY"))
        gr.Markdown("**LATEST OPPONENT CHALLENGE**")
        opponent_text_output = gr.HTML("<div style='padding: 15px; background: #111827; border-radius: 6px; border: 1px solid #374151; color: #d1d5db;'>Initialize environment to begin...</div>")

    # 3. Instruction Banner
    gr.HTML("""
        <div style="background-color: rgba(34, 197, 94, 0.1); border: 1px solid #22c55e; border-radius: 8px; padding: 12px; color: #d1d5db; margin-top: 15px; margin-bottom: 15px;">
            <strong>Environment Rules:</strong> Follow the strict progression: classify → route → respond. Utilize the auto-fill functionality to automatically populate the optimal evaluation payload for the current phase.
        </div>
    """)

    # 4. Step-by-step Action Area
    gr.Markdown("### Step-by-step action")
    with gr.Group():
        with gr.Row():
            topic_input = gr.Textbox(label="Debate Topic", value="Universal Basic Income is necessary", scale=3)
            difficulty_input = gr.Dropdown(label="Difficulty", choices=["Easy", "Medium", "Hard"], value="Medium", scale=1)
            
        phase_tag_input = gr.Dropdown(label="Action Type (Phase Tag)", choices=["OPENING", "CHALLENGE", "REBUTTAL", "CONSOLIDATION", "CLOSING"], value="OPENING")
        argument_input = gr.Textbox(label="Argument Payload (matches POST /step JSON)", lines=4)
        
        with gr.Row():
            execute_btn = gr.Button("EXECUTE STEP", variant="primary", scale=2)
            reset_btn = gr.Button("RESET ENVIRONMENT", scale=1)
            autofill_btn = gr.Button("⚡ AUTO-FILL IDEAL MOVE", scale=2)

    # 5. Custom Action Timeline
    gr.Markdown("### Action Timeline")
    timeline_output = gr.HTML(render_timeline([]))

    # --- Event Listeners ---
    
    # Auto-Fill Logic
    autofill_btn.click(
        fn=auto_fill_action,
        inputs=[current_phase_state],
        outputs=[phase_tag_input, argument_input]
    )

    # Reset Logic
    reset_btn.click(
        fn=reset_env_ui, 
        inputs=[topic_input, difficulty_input], 
        outputs=[last_step_card, total_rew_card, score_card, status_card, pills_html, opponent_text_output, timeline_output, timeline_state, total_reward_state, current_phase_state]
    )
    
    # Step/Execute Logic
    execute_btn.click(
        fn=step_env_ui, 
        inputs=[argument_input, phase_tag_input, timeline_state, total_reward_state, difficulty_input], 
        outputs=[last_step_card, total_rew_card, score_card, status_card, pills_html, opponent_text_output, timeline_output, timeline_state, total_reward_state, current_phase_state]
    )

# Mount on FastAPI
app = gr.mount_gradio_app(app, demo, path="/")

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=7860)